backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://yucatankidsmx.org/assets/images/logos/1MainLogoTRSPT.png

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Media & Events"
    folder: "src/blog"
    create: true
    slug: "{{pageName}}"
    fields:
      - {
          label: "Page-Name-with-dashes-only",
          name: "pageName",
          widget: "string",
        }
      - { label: "Title", name: "blogTitle", widget: "string" }
      - { label: "Title Tag", name: "titleTag", widget: "string" }
      - { label: "Description", name: "blogDescription", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
